# Generated by Django 5.2 on 2025-04-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], null=True, verbose_name='Гендер'),
        ),
    ]
