line-length = 88
target-version = "py311"

[lint]
select = ["E", "F", "W", "C90", "DJ01"]
extend-ignore = ["E501"]
per-file-ignores = { "**/migrations/*.py" = ["E501", "F401"] }

[format]
quote-style = "double"
line-ending = "lf"
skip-magic-trailing-comma = true
