# Generated by Django 5.2 on 2025-10-07 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='amount',
        ),
        migrations.AddField(
            model_name='productincart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productincart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во товара'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
