# Generated by Django 5.2 on 2025-10-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productincart_amount_productincart_added_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='amount',
            new_name='quantity',
        ),
    ]
