# Generated by Django 5.2 on 2025-10-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_amount_productinorder_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
