# Generated by Django 5.2 on 2025-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
    ]
