# Generated by Django 5.2 on 2025-10-07 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productinorder_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
