# Generated by Django 5.2 on 2025-10-15 11:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_cart_options_rename_create_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во товара'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.order', verbose_name='Заказ'),
        ),
    ]
